#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := AWS_IoT_EduKit-Factory_Firmware

include $(IDF_PATH)/make/project.mk

