#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := M5Core2ForAWSDemo
PROJECT_VER := 1.0.1

include $(IDF_PATH)/make/project.mk

